from langchain_core.callbacks.base import Callbacks
from minitap.mobile_use.sdk.types import AgentConfig, AgentProfile, DevicePlatform

class AgentConfigBuilder:
    def __init__(self) -> None: ...
    def for_device(self, platform: DevicePlatform, device_id: str) -> AgentConfigBuilder: ...
    def add_profile(self, profile: AgentProfile, validate: bool = True) -> AgentConfigBuilder: ...
    def with_default_profile(self, profile: str | AgentProfile) -> AgentConfigBuilder: ...
    def with_graph_config_callbacks(self, callbacks: Callbacks) -> AgentConfigBuilder: ...
    def build(self, validate_profiles: bool = True) -> AgentConfig: ...
