// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scenario } from "./Scenario";

export type ContractProbe = { run_id: string, observed_at: string, scenario: Scenario, nullable_note: string | null, optional_note?: string | null, counter: string, };
