// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";

export type HealthResponse = { status: HealthStatus, service: string, version: string, };
