"""Explicit Rust → OpenAPI/Hey API and worker schema/Pydantic pipeline, with drift detection."""
import argparse
import os
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ("apps/web/src/api/generated", "contracts/browser.openapi.json", "contracts/worker.schema.json", "apps/mobile-worker/src/mobile_qa_worker/generated/models.py")


def files(base: Path) -> dict[str, bytes]:
    result: dict[str, bytes] = {}
    for name in OUTPUTS:
        path = base / name
        if path.is_file():
            result[name] = path.read_bytes()
        elif path.is_dir():
            result.update({str(p.relative_to(base)): p.read_bytes() for p in path.rglob("*") if p.is_file()})
    return result


def synchronize(staged: Path, destination: Path, check: bool) -> list[str]:
    expected, current = files(staged), files(destination)
    changed = sorted(name for name in expected.keys() | current.keys() if expected.get(name) != current.get(name))
    if not check:
        for name in changed:
            path = destination / name
            if name not in expected:
                path.unlink()
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(expected[name])
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="mobile-qa-contracts-") as temp:
        staged = Path(temp)
        subprocess.run(["cargo", "run", "--locked", "--quiet", "-p", "mobile-qa-contracts", "--bin", "export-contracts", "--", str(staged)], cwd=ROOT, check=True)
        subprocess.run(["pnpm", "generate:sdk"], cwd=ROOT / "apps/web", env=os.environ | {"MOBILE_QA_OPENAPI_INPUT": str(staged / OUTPUTS[1]), "MOBILE_QA_SDK_OUTPUT": str(staged / OUTPUTS[0])}, check=True)
        output = staged / OUTPUTS[3]
        output.parent.mkdir(parents=True)
        subprocess.run(["uv", "run", "--no-sync", "--frozen", "datamodel-codegen", "--input", str(staged / OUTPUTS[2]), "--input-file-type", "jsonschema", "--output", str(output), "--output-model-type", "pydantic_v2.BaseModel", "--target-python-version", "3.12", "--use-standard-collections", "--use-union-operator", "--use-annotated", "--field-constraints", "--strict-nullable", "--extra-fields", "forbid", "--disable-timestamp", "--custom-file-header", "# Generated by just types. Do not edit."], cwd=ROOT / "apps/mobile-worker", check=True)
        changed = synchronize(staged, ROOT, args.check)
    if args.check and changed:
        print("Contract drift: " + ", ".join(changed))
        return 1
    print(f"Contracts {'checked' if args.check else 'generated'}: {len(changed)} changed files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
