//! First product schema. Explicit FK/check constraints protect tenant and lifecycle invariants.
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

fn composite_foreign_key(
    from_table: &str,
    from_columns: &[&str],
    to_table: &str,
    to_columns: &[&str],
) -> TableForeignKey {
    let mut key = TableForeignKey::new();
    key.from_tbl(Alias::new(from_table))
        .to_tbl(Alias::new(to_table));
    for column in from_columns {
        key.from_col(Alias::new(*column));
    }
    for column in to_columns {
        key.to_col(Alias::new(*column));
    }
    key
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("users"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("email"))
                            .text()
                            .not_null()
                            .unique_key()
                            .check(
                                Func::char_length(Expr::col(Alias::new("email"))).between(3, 254),
                            ),
                    )
                    .col(
                        ColumnDef::new(Alias::new("password_hash"))
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("display_name")).text().not_null())
                    .col(ColumnDef::new(Alias::new("disabled_at")).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("organizations"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("name")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("memberships"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("organization_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("role"))
                            .text()
                            .not_null()
                            .check(Expr::col(Alias::new("role")).is_in(["operator", "member"])),
                    )
                    .col(ColumnDef::new(Alias::new("active")).boolean().not_null())
                    .index(
                        Index::create()
                            .unique()
                            .col(Alias::new("user_id"))
                            .col(Alias::new("organization_id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("memberships"), Alias::new("user_id"))
                            .to(Alias::new("users"), Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("memberships"), Alias::new("organization_id"))
                            .to(Alias::new("organizations"), Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("sessions"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("csrf_token")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("expires_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("revoked_at")).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("sessions"), Alias::new("user_id"))
                            .to(Alias::new("users"), Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("login_attempts"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("bucket"))
                            .text()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("window_start"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("count"))
                            .integer()
                            .not_null()
                            .check(Expr::col(Alias::new("count")).gte(0)),
                    )
                    .col(
                        ColumnDef::new(Alias::new("expires_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("apps"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("organization_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("name")).text().not_null().check(
                            Func::char_length(Expr::col(Alias::new("name"))).between(1, 100),
                        ),
                    )
                    .col(
                        ColumnDef::new(Alias::new("android_package"))
                            .text()
                            .not_null()
                            .check(
                                Func::char_length(Expr::col(Alias::new("android_package")))
                                    .between(1, 255),
                            ),
                    )
                    .col(ColumnDef::new(Alias::new("created_by")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .col(Alias::new("organization_id"))
                            .col(Alias::new("android_package")),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .col(Alias::new("id"))
                            .col(Alias::new("organization_id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("apps"), Alias::new("organization_id"))
                            .to(Alias::new("organizations"), Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("apps"), Alias::new("created_by"))
                            .to(Alias::new("users"), Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("app_memberships"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("user_id")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("organization_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("app_id")).uuid().not_null())
                    .index(
                        Index::create()
                            .unique()
                            .col(Alias::new("user_id"))
                            .col(Alias::new("app_id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                Alias::new("app_memberships"),
                                (Alias::new("user_id"), Alias::new("organization_id")),
                            )
                            .to(
                                Alias::new("memberships"),
                                (Alias::new("user_id"), Alias::new("organization_id")),
                            ),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                Alias::new("app_memberships"),
                                (Alias::new("app_id"), Alias::new("organization_id")),
                            )
                            .to(
                                Alias::new("apps"),
                                (Alias::new("id"), Alias::new("organization_id")),
                            ),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("environments"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("organization_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("app_id"))
                            .uuid()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("name"))
                            .text()
                            .not_null()
                            .check(Func::char_length(Expr::col(Alias::new("name"))).between(1, 80)),
                    )
                    .col(
                        ColumnDef::new(Alias::new("backend_origins"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("login_origins"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("revision"))
                            .integer()
                            .not_null()
                            .check(Expr::col(Alias::new("revision")).gt(0)),
                    )
                    .col(ColumnDef::new(Alias::new("account_secret_reference_id")).uuid())
                    .col(ColumnDef::new(Alias::new("reset_secret_reference_id")).uuid())
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .col(Alias::new("id"))
                            .col(Alias::new("app_id"))
                            .col(Alias::new("organization_id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                Alias::new("environments"),
                                (Alias::new("app_id"), Alias::new("organization_id")),
                            )
                            .to(
                                Alias::new("apps"),
                                (Alias::new("id"), Alias::new("organization_id")),
                            ),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("secret_references"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("organization_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("app_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("label")).text().not_null())
                    .col(ColumnDef::new(Alias::new("locator")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("kind"))
                            .text()
                            .not_null()
                            .check(Expr::col(Alias::new("kind")).is_in(["account", "reset"])),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .col(Alias::new("id"))
                            .col(Alias::new("app_id"))
                            .col(Alias::new("organization_id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                Alias::new("secret_references"),
                                (Alias::new("app_id"), Alias::new("organization_id")),
                            )
                            .to(
                                Alias::new("apps"),
                                (Alias::new("id"), Alias::new("organization_id")),
                            ),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("environment_checks"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("organization_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("app_id")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("environment_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("environment_revision"))
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("kind")).text().not_null().check(
                        Expr::col(Alias::new("kind")).is_in(["backend", "account", "reset"]),
                    ))
                    .col(
                        ColumnDef::new(Alias::new("state")).text().not_null().check(
                            Expr::col(Alias::new("state"))
                                .is_in(["operator_reported_ok", "operator_reported_blocked"]),
                        ),
                    )
                    .col(ColumnDef::new(Alias::new("note")).text())
                    .col(ColumnDef::new(Alias::new("checked_by")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("checked_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                Alias::new("environment_checks"),
                                (
                                    Alias::new("environment_id"),
                                    Alias::new("app_id"),
                                    Alias::new("organization_id"),
                                ),
                            )
                            .to(
                                Alias::new("environments"),
                                (
                                    Alias::new("id"),
                                    Alias::new("app_id"),
                                    Alias::new("organization_id"),
                                ),
                            ),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("environment_checks"), Alias::new("checked_by"))
                            .to(Alias::new("users"), Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("build_uploads"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("organization_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("app_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("created_by")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("original_filename"))
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("expected_size"))
                            .big_integer()
                            .not_null()
                            .check(
                                Expr::col(Alias::new("expected_size")).gt(0).and(
                                    Expr::col(Alias::new("expected_size")).lte(262_144_000_i64),
                                ),
                            ),
                    )
                    .col(ColumnDef::new(Alias::new("state")).text().not_null().check(
                        Expr::col(Alias::new("state")).is_in([
                            "pending",
                            "receiving",
                            "uploaded",
                            "finalized",
                            "expired",
                        ]),
                    ))
                    .col(
                        ColumnDef::new(Alias::new("expires_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("attempt_id")).uuid())
                    .col(ColumnDef::new(Alias::new("lease_until")).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(Alias::new("storage_backend"))
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("sealed_storage_key")).text())
                    .col(
                        ColumnDef::new(Alias::new("actual_size"))
                            .big_integer()
                            .check(
                                Expr::col(Alias::new("actual_size")).is_null().or(Expr::col(
                                    Alias::new("actual_size"),
                                )
                                .gt(0)
                                .and(
                                    Expr::col(Alias::new("actual_size"))
                                        .eq(Expr::col(Alias::new("expected_size"))),
                                )),
                            ),
                    )
                    .col(ColumnDef::new(Alias::new("sha256")).text())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .index(
                        Index::create()
                            .unique()
                            .col(Alias::new("id"))
                            .col(Alias::new("app_id"))
                            .col(Alias::new("organization_id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                Alias::new("build_uploads"),
                                (Alias::new("app_id"), Alias::new("organization_id")),
                            )
                            .to(
                                Alias::new("apps"),
                                (Alias::new("id"), Alias::new("organization_id")),
                            ),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("build_uploads"), Alias::new("created_by"))
                            .to(Alias::new("users"), Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("builds"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("organization_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("app_id")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("upload_id"))
                            .uuid()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("storage_backend"))
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("storage_key")).text().not_null())
                    .col(ColumnDef::new(Alias::new("sha256")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("byte_size"))
                            .big_integer()
                            .not_null()
                            .check(
                                Expr::col(Alias::new("byte_size"))
                                    .gt(0)
                                    .and(Func::char_length(Expr::col(Alias::new("sha256"))).eq(64)),
                            ),
                    )
                    .col(
                        ColumnDef::new(Alias::new("original_filename"))
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("validation_state"))
                            .text()
                            .not_null()
                            .check(Expr::col(Alias::new("validation_state")).is_in([
                                "validating",
                                "validated",
                                "invalid",
                                "unsupported",
                                "error",
                            ])),
                    )
                    .col(ColumnDef::new(Alias::new("reason_code")).text())
                    .col(ColumnDef::new(Alias::new("message")).text())
                    .col(ColumnDef::new(Alias::new("metadata")).json_binary())
                    .col(
                        ColumnDef::new(Alias::new("validator_version"))
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("intake_policy_version"))
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("attempt_id")).uuid())
                    .col(ColumnDef::new(Alias::new("lease_until")).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("started_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("validated_at"))
                            .timestamp_with_time_zone()
                            .check(
                                Expr::col(Alias::new("validation_state"))
                                    .ne("validated")
                                    .or(Expr::col(Alias::new("metadata"))
                                        .is_not_null()
                                        .and(Expr::col(Alias::new("validated_at")).is_not_null())),
                            ),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                Alias::new("builds"),
                                (
                                    Alias::new("upload_id"),
                                    Alias::new("app_id"),
                                    Alias::new("organization_id"),
                                ),
                            )
                            .to(
                                Alias::new("build_uploads"),
                                (
                                    Alias::new("id"),
                                    Alias::new("app_id"),
                                    Alias::new("organization_id"),
                                ),
                            ),
                    )
                    .to_owned(),
            )
            .await?;

        let account_secret_key = composite_foreign_key(
            "environments",
            &["account_secret_reference_id", "app_id", "organization_id"],
            "secret_references",
            &["id", "app_id", "organization_id"],
        );
        let reset_secret_key = composite_foreign_key(
            "environments",
            &["reset_secret_reference_id", "app_id", "organization_id"],
            "secret_references",
            &["id", "app_id", "organization_id"],
        );
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("environments"))
                    .add_foreign_key(&account_secret_key)
                    .add_foreign_key(&reset_secret_key)
                    .to_owned(),
            )
            .await?;
        for (name, table, columns) in [
            ("sessions_expiry", "sessions", vec!["expires_at"]),
            ("sessions_user", "sessions", vec!["user_id"]),
            (
                "uploads_app_created",
                "build_uploads",
                vec!["app_id", "created_at", "id"],
            ),
            (
                "uploads_state_expiry",
                "build_uploads",
                vec!["state", "expires_at"],
            ),
            (
                "builds_app_created",
                "builds",
                vec!["app_id", "created_at", "id"],
            ),
            (
                "checks_environment_revision",
                "environment_checks",
                vec!["environment_id", "environment_revision", "checked_at"],
            ),
        ] {
            let mut index = Index::create();
            index.name(name).table(Alias::new(table));
            for column in columns {
                index.col(Alias::new(column));
            }
            manager.create_index(index.to_owned()).await?;
        }
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("environments"))
                    .drop_column(Alias::new("account_secret_reference_id"))
                    .drop_column(Alias::new("reset_secret_reference_id"))
                    .to_owned(),
            )
            .await?;
        for table in [
            "builds",
            "build_uploads",
            "environment_checks",
            "secret_references",
            "environments",
            "app_memberships",
            "apps",
            "login_attempts",
            "sessions",
            "memberships",
            "organizations",
            "users",
        ] {
            manager
                .drop_table(Table::drop().table(Alias::new(table)).to_owned())
                .await?;
        }
        Ok(())
    }
}
